cpims/urls.py
"""
cpims URL Configuration.

Other urls are import
Put here only urls not specific to app
"""
from . import views
import cpovc_auth
import cpovc_access
from django.urls import include, path, re_path
from django.contrib import admin
from cpovc_auth import urls as auth_urls
from cpovc_registry import urls as registry_urls
from cpovc_registry import views as registry_views

from cpovc_forms import urls as forms_urls
from cpovc_reports import urls as reports_urls
from cpovc_gis import urls as gis_urls
from cpovc_api import urls as api_urls
from cpovc_ovc import urls as ovc_urls
from cpovc_settings import urls as settings_urls
from cpovc_manage import urls as manage_urls
from cpovc_help import urls as help_urls
from notifications import urls as noti_urls
from cpovc_ctip import urls as ctip_urls
from cpovc_afc import urls as ac_urls
from cpovc_stat_inst import urls as si_urls

from django.views.generic import TemplateView
# For dashboard
from cpovc_dashboard import urls as dashboard_api_urls
from cpovc_dashboard import views as dash_views


urlpatterns = [
    path('admin/', admin.site.urls),
    # url(r'^$', 'cpovc_auth.views.log_in', name='home'),
    path('', views.home, name='home'),
    path('accounts/request/', views.access, name='access'),
    path('accounts/terms/<int:id>/', cpovc_access.views.terms,
         name='terms'),
    path('register/', cpovc_auth.views.register, name='register'),
    path('auth/', include(auth_urls)),
    path('registry/', include(registry_urls)),
    path('forms/', include(forms_urls)),
    path('reports/', include(reports_urls)),
    path('gis/', include(gis_urls)),
    path('api/v1/', include(api_urls)),
    path('ovc_care/', include(ovc_urls)),
    path('settings/', include(settings_urls)),
    path('manage/', include(manage_urls)),
    path('help/', include(help_urls)),
    path('forms/ctip/', include(ctip_urls)),
    path('forms/altcare/', include(ac_urls)),
    path('notifications/', include(noti_urls, namespace='notifications')),
    re_path(r'^dashboard/(?P<did>[A-Z{2}]+)/$',
            registry_views.dashboard, name='dashboard'),
    # Accounts management
    path('accounts/', include(cpovc_auth.urls)),
    # Override Login and Logout not to use the /accounts/*
    path('login/', cpovc_auth.views.log_in, name='login'),
    path('logout/', cpovc_auth.views.log_out, name='logout'),
    path('d/', dash_views.ovc_dashboard, name='ovc_dashboard'),
    re_path(r'^api/v2/', include(dashboard_api_urls)),
    # SI Module
    path('institutions/si/', include(si_urls)),
    re_path(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt',
                                                   content_type='text/plain'))]

handler400 = 'cpims.views.handler_400'
handler404 = 'cpims.views.handler_404'
handler500 = 'cpims.views.handler_500'

admin.site.site_header = 'CPIMS Administration'
admin.site.site_title = 'CPIMS administration'
admin.site.index_title = 'CPIMS admin'

cpovc_afc/urls.py
from django.urls import path, re_path
from . import views

# This should contain urls related to Care reforms ONLY
urlpatterns = [
    path('', views.alt_care_home, name='alternative_care'),
    path(
        'new/<uuid:case_id>/', views.new_alternative_care,
        name='new_alt_care'),
    path(
        'view/<uuid:care_id>/', views.view_alternative_care,
        name='view_alt_care'),
    path(
        'edit/<uuid:care_id>/', views.edit_alternative_care,
        name='edit_alt_care'),
    re_path(r'^(?P<cid>[A-Z{2}]+)/(?P<form_id>\d+[A-Z_\-{1}]+)/(?P<care_id>[0-9A-Za-z_\-{32}]+)/$',
            views.alt_care_form, name='alt_care_form'),
    re_path(r'^(?P<cid>[A-Z{2}]+)/(?P<form_id>\d+[A-Z_\-{1}]+)/(?P<care_id>[0-9A-Za-z_\-{32}]+)/(?P<ev_id>\d+)/$',
            views.edit_alt_care_form, name='edit_alt_care_form'),
    re_path(r'^(?P<form_id>\d+[A-Z_\-{1}]+)/(?P<event_id>[0-9A-Za-z_\-{32}]+)/$',
            views.delete_alt_care_form, name='delete_alt_care_form'),
]

cpovc_ctip/urls.py
from django.urls import path, re_path
from . import views

# This should contain urls related to CTiP ONLY
urlpatterns = [
    path('', views.ctip_home, name='ctip_home'),
    re_path(r'^case/(?P<case_id>[0-9A-Za-z_\-{32}]+)/$', views.view_ctip_case, name='view_ctip_case'),
    re_path(r'^form/(?P<form_id>[A-Z{1}]+)/(?P<case_id>[0-9A-Za-z_\-{32}]+)/(?P<id>\d+)/$',
            views.ctip_forms, name='ctip_forms'),
    re_path(r'^form/(?P<form_id>[A-Z{1}]+)/(?P<case_id>[0-9A-Za-z_\-{32}]+)/$',
            views.ctip_form, name='ctip_form'),
    re_path(r'^form/view/(?P<form_id>[A-Z{1}]+)/(?P<case_id>[0-9A-Za-z_\-{32}]+)/$',
            views.view_ctip_form, name='view_ctip_form'),
    path('new/<uuid:case_id>/', views.new_ctip_case, name='new_ctip_case'),
    path('edit/<uuid:case_id>/', views.edit_ctip_case, name='edit_ctip_case'),
]

notifications/urls.py
''' Django notification urls file '''
# -*- coding: utf-8 -*-
from distutils.version import StrictVersion
# pylint: disable=no-name-in-module,import-error

from django import get_version

from . import views

if StrictVersion(get_version()) >= StrictVersion('2.0'):
    from django.urls import re_path as pattern
else:
    from django.conf.urls import url as pattern


urlpatterns = [
    pattern(r'^$', views.notifications_home, name='home'),
    pattern(r'^(?P<id>\d+)/$', views.notifications_read, name='read'),
    pattern(r'^all/$', views.AllNotificationsList.as_view(), name='all'),
    pattern(r'^unread/$', views.UnreadNotificationsList.as_view(), name='unread'),
    pattern(r'^mark-all-as-read/$', views.mark_all_as_read, name='mark_all_as_read'),
    pattern(r'^mark-as-read/(?P<slug>\d+)/$', views.mark_as_read, name='mark_as_read'),
    pattern(r'^mark-as-unread/(?P<slug>\d+)/$', views.mark_as_unread, name='mark_as_unread'),
    pattern(r'^delete/(?P<slug>\d+)/$', views.delete, name='delete'),
    pattern(r'^api/unread_count/$', views.live_unread_notification_count, name='live_unread_notification_count'),
    pattern(r'^api/all_count/$', views.live_all_notification_count, name='live_all_notification_count'),
    pattern(r'^api/unread_list/$', views.live_unread_notification_list, name='live_unread_notification_list'),
    pattern(r'^api/all_list/', views.live_all_notification_list, name='live_all_notification_list'),
]

app_name = 'notifications'

cpovc_afc/forms.py
from django import forms
from django.forms.widgets import RadioSelect

from django.utils.translation import gettext_lazy as _

from cpovc_main.functions import get_list, get_lists
immunization_list = get_list('immunization_status_id', 'Please Select')

person_type_list = get_list('person_type_id', 'Please Select Type')
school_level_list = get_list('school_level_id', 'Please Select Level')
admission_list = get_list('school_type_id', 'Please Select one')
disability_list = get_list('disability_type_id', 'Please Select one')
severity_list = get_list('severity_level_id', 'Please Select one')
admission_type_list = get_list('admission_type_id', 'Please Select')
admission_reason_list = get_list('care_admission_reason_id')
domain_list = get_list('afc_domain_id', 'Please Select')
list_sex_id = get_list('sex_id')
consent_forms_list = get_list('consent_forms', 'Please Select')
# new listings
list_other_adms = get_list('other_form_admission', 'Please Select')
list_other_vulnerability = get_list(
    'vulnerability_at_admission', 'Please Select')
list_relationship = get_list('relationship_type_id', 'Please Select')
list_education_perf = get_list('education_performance')
list_marriage_type = get_list('parents_marriage_type', 'Please Select')
list_items_count = get_list('items_count_id', 'Please Select')
list_special_support = get_list('special_support')
list_community_services = get_list('community_services')
list_school_category = get_list('school_category_id', 'Please Select')
list_range_level = get_list('attachment_level', 'Please Select')
list_range_level_rdo = get_lists(['attachment_level', 'na_option'])
list_child_exhibits = get_list('child_exhibits')
list_income_range = get_list('income_range', 'Please Select')
list_employment_type = get_list('employment_type', 'Please Select')
list_closure_reasons = get_list('case_closure_reasons', 'Please Select')
list_case_transfer_ids = get_list('case_transfer_ids', 'Please Select')
list_satisfied_level = get_list('satisfied_level_ids')
list_feeling_level = get_list('feeling_level_ids')
list_referral_reasons = get_list('referral_reasons_ids', 'Please Select')
list_referral_documents = get_list('referral_documents_ids')
list_case_plan_responsible = get_list('case_plan_responsible')

disability_actions = get_list('disability_actions')
list_family_types = get_list('family_type_id', 'Please Select')

YESNO_UN_CHOICES = get_list('yesno_una')
list_disability_assessment = get_list('disability_assessment_id')
list_disability_handling = get_list('disability_handling_id')
list_attachment_assessment = get_list(
    'attachment_assessment_id', 'Please select')


YESNO_CHOICES = get_list('yesno_id')
YESNO_UK_CHOICES = get_lists(['yesno_id', 'uk_option'])
care_option_list = get_list(
    'alternative_family_care_type_id', 'Please Select Care')

disability_degree = (('0', '0'), ('1', '1'), ('2', '2'),
                     ('3', '3'), ('4', '4'), )

YESNONA_choices = get_list('yesno_na')
list_sex_other_id = get_list('sex_id', 'Please Select')
list_ratings = get_list('ratings_id')
list_frequency = get_lists(['period_frequency_id', 'na_option'])


class RadioCustomRenderer(RadioSelect):
    """Custom radio button renderer class."""

    def render(self):
        """Renderer override method."""
        pass


class AltCareForm(forms.Form):
    """AFC form."""

    has_consent = forms.ChoiceField(
        choices=YESNO_CHOICES,
        required=True,
        widget=forms.RadioSelect(
            # renderer=RadioCustomRenderer,
            attrs={'id': 'has_consent',
                   'data-parsley-required': 'true',
                   'data-parsley-errors-container': "#has_consent_error"}))

    care_option = forms.ChoiceField(
        choices=care_option_list,
        initial='0',
        widget=forms.Select(
            attrs={'class': 'form-control', 'id': 'care_option',
                   'data-parsley-required': "true"}))

    care_sub_option = forms.ChoiceField(
        choices=(('', 'Please Select'), ),
        required=False,
        widget=forms.Select(
            attrs={'class': 'form-control', 'id': 'care_sub_option',
                   'data-parsley-required': "false"}))

    case_date = forms.DateField(widget=forms.TextInput(
        attrs={'placeholder': _('Care initiation Date'),
               'class': 'form-control',
               'id': 'case_date',
               'data-parsley-required': "true"
               }))

    event_date = forms.DateField(widget=forms.TextInput(
        attrs={'placeholder': _('Date'),
               'class': 'form-control',
               'id': 'event_date',
               'data-parsley-required': "true"
               }))

    AFC_FM_msc = forms.MultipleChoiceField(
        choices=admission_reason_list,
        widget=forms.CheckboxSelectMultiple(
            attrs={'data-parsley-required': 'true',
                   'data-parsley-errors-container': "#id_qf1A1"}))

    qf3A1_rdo = forms.ChoiceField(
        choices=YESNO_CHOICES,
        required=True,
        widget=forms.RadioSelect(
            # renderer=RadioCustomRenderer,
            attrs={'id': 'qf3A1_rdo',
                   'data-parsley-required': 'true',
                   'data-parsley-errors-container': "#qf3A1_rdo_error"}))

    qf3A2_sdd = forms.ChoiceField(
        choices=consent_forms_list,
        initial='0',
        widget=forms.Select(
            attrs={'class': 'form-control', 'id': 'care_option',
                   'data-parsley-required': "true"}))

    qf3B1_rdo = forms.ChoiceField(
        choices=YESNO_CHOICES,
        required=True,
        widget=forms.RadioSelect(
            # renderer=RadioCustomRenderer,
            attrs={'id': 'qf3B1_rdo',
                   'data-parsley-required': 'true',
                   'data-parsley-errors-container': "#qf3B1_rdo_error"}))


class AFCForm1A(forms.Form):
    """AFC Form 1A."""

    event_date = forms.DateField(widget=forms.TextInput(
        attrs={'placeholder': _('Date'),
               'class': 'form-control',
               'id': 'event_date',
               'data-parsley-required': "true"
               }))

    qf1A1_rdo = forms.ChoiceField(
        choices=YESNO_CHOICES,
        required=True,
        widget=forms.RadioSelect(
            # renderer=RadioCustomRenderer,
            attrs={'id': 'has_bcert',
                   'data-parsley-required': 'true',
                   'data-parsley-errors-container': "#qf1A1_rdo_error"}))

    qf1A2 = forms.CharField(required=False, widget=forms.TextInput(
        attrs={'placeholder': _(''),
               'class': 'form-control', 'id': 'qf1A2',
               'data-parsley-required': "false"}))

    qf1A3 = forms.CharField(required=False, widget=forms.TextInput(
        attrs={'placeholder': _(''),
               'class': 'form-control', 'id': 'qf1A3',
               'data-parsley-required': "false"}))

    qf1A4 = forms.CharField(required=False, widget=forms.TextInput(
        attrs={'placeholder': _(''),
               'class': 'form-control', 'id': 'qf1A4',
               'data-parsley-required': "false"}))

    qf1A5 = forms.CharField(required=False, widget=forms.TextInput(
        attrs={'placeholder': _(''),
               'class': 'form-control', 'id': 'qf1A5',
               'data-parsley-required': "false"}))

    qf1A6 = forms.CharField(required=False, widget=forms.TextInput(
        attrs={'placeholder': _(''),
               'class': 'form-control', 'id': 'qf1A6',
               'data-parsley-required': "false"}))

    qf1A7 = forms.CharField(required=False, widget=forms.TextInput(
        attrs={'placeholder': _(''),
               'class': 'form-control', 'id': 'qf1A7',
               'data-parsley-required': "false"}))

    qf1A8 = forms.CharField(required=False, widget=forms.TextInput(
        attrs={'placeholder': _(''),
               'class': 'form-control', 'id': 'qf1A8',
               'data-parsley-required': "false"}))

    qf1A10_rdo = forms.ChoiceField(
        choices=YESNO_CHOICES,
        required=True,
        widget=forms.RadioSelect(
            # renderer=RadioCustomRenderer,
            attrs={'id': 'has_disability',
                   'data-parsley-required': 'true',
                   'data-parsley-errors-container': "#qf1A2_rdo_error"}))

    qf1A11_sdd = forms.ChoiceField(
        choices=disability_list,
        initial='0',
        required=False,
        widget=forms.Select(
            attrs={'class': 'form-control',
                   'id': 'disability_type'}))

    qf1A12_sdd = forms.ChoiceField(
        choices=severity_list,
        initial='0',
        required=False,
        widget=forms.Select(
            attrs={'class': 'form-control',
                   'id': 'disability_severity'}))

    qf1A13 = forms.CharField(required=False, widget=forms.TextInput(
        attrs={'placeholder': _(''),
               'class': 'form-control', 'id': 'qf1A13',
               'data-parsley-required': "false"}))

    qf1A14_sdd = forms.ChoiceField(
        choices=list_other_adms,
        initial='0',
        required=False,
        widget=forms.Select(
            attrs={'class': 'form-control',
                   'id': 'qf1A14_sdd'}))

    qf1A15_rdo = forms.ChoiceField(
        choices=YESNO_CHOICES,
        required=True,
        widget=forms.RadioSelect(
            # renderer=RadioCustomRenderer,
            attrs={'data-parsley-required': 'true',
                   'data-parsley-errors-container': "#qf1A15_rdo_error"}))

    qf1A16 = forms.CharField(required=False, widget=forms.TextInput(
        attrs={'placeholder': _(''),
               'class': 'form-control',
               'data-parsley-required': "false"}))

    qf1A17 = forms.DateField(required=False, widget=forms.TextInput(
        attrs={'placeholder': _(''),
               'class': 'form-control event_date',
               'data-parsley-required': "false"}))

    qf1A18 = forms.CharField(required=False, widget=forms.TextInput(
        attrs={'placeholder': _(''),

templates/stat_inst-/change_in_profile.html
{% extends 'base.html' %}
{% load static %}
{% block page_title %} Bio Data {{ form_name }}{% endblock %}

{% load app_filters %}

{% load crispy_forms_tags %}

{% block style_code %}
<link href="{% static 'plugins/parsley/src/parsley.css' %}" rel="stylesheet" />
<link href="{% static 'plugins/bootstrap-datepicker/css/datepicker3.css' %}" rel="stylesheet" />

<link href="{% static 'plugins/bootstrap-wizard/css/bwizard.min.css' %}" rel="stylesheet" />
<style type="text/css">
form#new-form-b ul {
      list-style-type: none;
    }
  form#new-form-b li {
      padding-left: 1em;
      text-indent: -2em;
  }
  @media screen {
  div.divHeader {
    display: none;
  }
}
@media print {
  div.divHeader {
    text-align: center;
    font-size: 16px;
    top: 0;
  }
  div.invoice-footer {
    bottom: 0 !important;
  }
  div#printId{
    display: none;
  }
  #wizard_a ol { display: none; }
  .bwizard-buttons { display: none; }
  .bwizard-steps { display: none; }
  #wizard_a ol li { display: none; }
  #step2, #step3  { display: block !important; }
  .control-label {margin-bottom: 5px;}
}
table {
    width: 100%;
    border-collapse: collapse;
  }
  
  th,td{
    padding: 10px;
    text-align: left; 
    border-bottom: 1px solid #ddd;
  }
  
  th {
    background-color: #f2f2f2;
    font-weight: bold;
  }
.custom-margin {
      margin-left: 10em;
    }
.table-margin {
        margin-left: 10px;
      }
</style>
{% endblock %}

{% block primary %}
<!-- begin breadcrumb -->
<ol class="breadcrumb pull-right">
	<li><a href="#">Home</a></li>
	<li class="active">Bio Data </li>
</ol>
<!-- end breadcrumb -->
<!-- begin page-header -->
<h1 class="page-header"> Form {{ form_id }} - {{ form_name }} <small>Home</small></h1>
<!-- end page-header -->
{% if messages %}
<div id="messages" class="alert alert-suc{{ form_name }}cess fade in">
    <span class="close" data-dismiss="alert">×</span>
    <i class="fa fa-check fa-2x pull-left"></i>
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.info %} class="{{ message.info }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
</div>
{% endif %}
<!-- begin row -->
<div class="row">
   <div class="col-md-12">
        <!-- begin panel -->
        <div class="panel panel-inverse" data-sortable-id="form-stuff-1">
            <div class="myForm">
            <div class="divHeader"><img src="{% static 'img/logo_gok.png' %}"><br/>MINISTRY OF LABOUR AND SOCIAL PROTECTION
            <br/>STATE DEPARTMENT OF SOCIAL PROTECTION <br/>DIRECTORATE OF CHILDREN SERVICES <br/><br/>
            <b>Statutory Institution - FORM {{ form_id }} - {{ form_name }}</b></div>
            <div class="cinvoice">
                <div class="invoice-company">
                    <span class="pull-right hidden-print">
                    <a href="javascript:;" class="btn btn-sm btn-danger m-b-10"><i class="fa fa-download m-r-5"></i> Export as PDF</a>
                    <button type="button" id="map-print" class="btn btn-sm btn-danger m-b-10" onclick="printChart()"><i class="fa fa-print"></i> Print Form</button>
                    {% if care %}
                    <a href="{% url 'view_alt_care' care_id=case.care_id|stringformat:'s' %}" class="btn btn-sm btn-success m-b-10"><i class="fa fa-mail-reply-all m-r-5"></i> Back to Care details</a>
                    {% else %}
                   
                    {% endif %}
                    </span>
                    <!-- Case No: {{ case_num }} :: {{ case.case.case_serial }} -->

                </div>
            </div>
            <div class="panel-body">
                <form class="form-horizontal" method="POST" id="new-form-1a" action="." data-parsley-validate="true">
                    {% csrf_token %}
                    <input type="hidden" name="form_id" value="{{ form_id }}">
                    <input type="hidden" name="case_id" value="{{ case.case_id }}">
                    <input type="hidden" name="person_id" value="{{ case.person.id }}">
                    <input type="hidden" name="care_id" value="{{ case.care_id }}">

                    <div id="wizard_a">
                        <ol>
                            <li>
                                Child's Profile
                                <small>CHANGE IN THE PROFILE OF A CHILD UNDER ENVIRONMENTAL ADJUSTMENT</small>
                            </li>
                        </ol>
                        <!-- begin wizard step-1 -->
                        <div class="tab-pane">
                            <fieldset>
                                <legend class="pull-left width-full">Profile</legend>

                                <div class="form-group">
                                      
                                        <label class="col-md-2 control-label">Date</label>
                                        <div class="col-md-3">
                                            {{ form.record_date }}
                                        </div>
                                </div>

                                <hr>

                                <div class="form-group">
                                        <label class="col-md-2 control-label">Name of Institution</label>
                                        <div class="col-md-3">
                                            {{ form.name_of_institution }}
                                        </div>
                                </div>

                                <div class="form-group">
                                    <label class="col-md-2 control-label">SCCO Addressed</label>
                                    <div class="col-md-3">{{ form.scco_addressed }}</div>
                                </div>
                                <div class="form-group">
                                        <label class="col-md-2 control-label">Old address to be released to</label>
                                        <div class="col-md-3">
                                            {{ form.old_released_to }}
                                        </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-2 control-label">Job of guardian</label>
                                    <div class="col-md-3">
                                        {{ form.guardian_job }}
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-2 control-label">New address to be released to</label>
                                    <div class="col-md-3">
                                        {{ form.new_released_to }}
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-2 control-label">Relation with the guardian</label>
                                    <div class="col-md-3">
                                        {{ form.relation_guardian }}
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-2 control-label">Expiration date</label>
                                    <div class="col-md-3">
                                        {{ form.expiration_date }}
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-2 control-label">Reason for change</label>
                                    <div class="col-md-3">
                                        {{ form.reason_forchange }}
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-2 control-label">Life planning (interest and aptitude)</label>
                                    <div class="col-md-3">
                                        {{ form.life_planning }}
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-2 control-label">Mental and Physical states</label>
                                    <div class="col-md-3">
                                        {{ form.mental_state }}
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-2 control-label">Other Changes</label>
                                    <div class="col-md-3">
                                        {{ form.other_changes }}
                                    </div>
                                </div>

                        </div>
                        <!-- end wizard step-3 -->
                    </div>
                    <form method="post" >
                        <!-- form fields -->
                        <div class="form-group" id="printId">
                            <label class="col-md-2 control-label"></label>
                            <div class="col-md-3">
                            <button type="submit" class="btn btn-sm btn-success">Submit Form {{ form_id }} details</button>
                            </div>
                        </div>
                    </form>
                </form>
            </div>
        </div>
    </div>
        <!-- end panel -->
    </div>
    
</div>
<!-- end row -->

{% endblock %}

{% block lazy_javascript_code %}


<script src="{% static 'plugins/bootstrap-wizard/js/bwizard.js' %}"></script>
<script>

$(document).ready(function() {
    $('#event_date, .event_date').datepicker({ endDate: '0y', format: 'dd-M-yyyy' });

    $("#wizard_a").bwizard({ validating: function (e, ui) { }            
    });

    
    // Handle disability
    var aval = $("input[name='qf1A10_rdo']:checked").val();
        handle_disability(aval);
    $('input[type=radio][name=qf1A10_rdo]').change(function() {
        handle_disability(this.value);
    });

    // Handle toggle for birth certificate
    var avalr = $("input[name='qf1A1_rdo']:checked").val();
        handle_toggle(avalr, 1);
    $('input[type=radio][name=qf1A1_rdo]').change(function() {
        handle_toggle(this.value, 1);
    });
    // Handle toggle for committal
    var avalr2 = $("input[name='qf1A15_rdo']:checked").val();
        handle_toggle(avalr2, 2);
    $('input[type=radio][name=qf1A15_rdo]').change(function() {
        handle_toggle(this.value, 2);
    }); 

});

function printChart() {
      //Print Chart
      var mapContainer;
      var body               = $('body');
      mapContainer       = $('div.myForm');
      if (mapContainer.length == 0){
          mapContainer = $('div.myForm');
      }
      var mapContainerParent = mapContainer.parent();
      var printContainer     = $('<div>');
      $(':input').removeAttr('placeholder');

      printContainer
        .addClass('print-container')
        .css('width', '100%')
        .css('height', '800px')
        .css('-webkit-print-color-adjust','exact')
        .height(mapContainer.height())
        .append(mapContainer)
        .prependTo(body);

      var content = body
        .children()
        .not('script')
        .not(printContainer)
        .detach();
      
      // Patch for some Bootstrap 3.3.x `@media print` styles. :|
      var patchedStyle = $('<style>')
        .attr('media', 'print')
        .text('img { max-width: auto !important; }' +
              'a[href]:after { content: ""; }')
        .appendTo('head');

      window.print();

      body.prepend(content);
      mapContainerParent.prepend(mapContainer);

      printContainer.remove();
      patchedStyle.remove();
      $('#print_title').remove();
}

function handle_disability(has_disb){
    if (has_disb == 'ANNO') {
        $('#disability_details_div').hide();
        $('#disability_severity').attr("data-parsley-required", "false");
        $('#disability_type').attr("data-parsley-required", "false");
    }else{
        $('#disability_details_div').show();
        $('#disability_severity').attr("data-parsley-required", "true");
        $('#disability_type').attr("data-parsley-required", "true");
    }

}

function handle_toggle(elem, itm){
    console.log('here '+ elem)
    if (itm == 1){
        if (elem == 'ANNO') {
            $("#qf1A2").prop("readonly", true);
        }else{
            $("#qf1A2").prop("readonly", false);
        }
    }else if (itm == 2){
        if (elem == 'ANNO') {
            $("#id_qf1A16").prop("readonly", true);
            $("#id_qf1A17").prop("readonly", true);
        }else{
            $("#id_qf1A16").prop("readonly", false);
            $("#id_qf1A17").prop("readonly", false);
        }
    }
    

}
</script>
{% endblock %}